### PR TITLE
Update licenses

### PR DESCRIPTION
**Pull request by jayfk**
This PR adds:

- a couple of common licenses in the Python eco-system (ZPL, Python)
- the GPL license family to also include the "and-later" and "only" SPDX ids
- adds a couple of older MPL ids

Sorry about the formatting. The GitHub UI apparently reformatted my input, making the diff kind of hard to read.

If required, I'd be happy to rebase/resubmit this PR.

### CODE REVIEW

**Comment by andrew** [comment]
Awesome, thanks! I'll sort out the formatting, merge and push a new release once I get out of my next meeting

**Comment by jayfk** [comment]
Exciting times at tidelift, huh!

**Comment by jayfk** [comment]
Argh, I just realized the test are failing because I’ve copy & pasted an additional ‘ somewhere.

Sorry for this trash PR.

**Comment by andrew** [comment]
Yeah exciting times, I'm still going to be mostly working on Libraries.io but lots of good stuff being built on top of it at DependencyCI/Tidelift

**Comment by andrew** [comment]
Looks like it was just an extra and a missing comma

**Comment by andrew** [comment]
Published as v3.1.0 https://rubygems.org/gems/license-compatibility/versions/3.1.0

**Pull request merged**
